// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOTVygWT2VnDWrGrarO4IBoXmhcne_MV8',
    appId: '1:17698616303:web:1f32dc5c188a61cb7d7c1a',
    messagingSenderId: '17698616303',
    projectId: 'goldfish-pos',
    authDomain: 'goldfish-pos.firebaseapp.com',
    storageBucket: 'goldfish-pos.firebasestorage.app',
    measurementId: 'G-CQ01VBFW1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMyDbLYLGNtr5zlWHLpajGOjSzn89RepU',
    appId: '1:17698616303:android:c05ef84f2f681a157d7c1a',
    messagingSenderId: '17698616303',
    projectId: 'goldfish-pos',
    storageBucket: 'goldfish-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0W19n1AKUc0CT9OPtSU3KznHk3ccoIIQ',
    appId: '1:17698616303:ios:512b7e0f688a45747d7c1a',
    messagingSenderId: '17698616303',
    projectId: 'goldfish-pos',
    storageBucket: 'goldfish-pos.firebasestorage.app',
    iosBundleId: 'com.example.goldfishPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0W19n1AKUc0CT9OPtSU3KznHk3ccoIIQ',
    appId: '1:17698616303:ios:512b7e0f688a45747d7c1a',
    messagingSenderId: '17698616303',
    projectId: 'goldfish-pos',
    storageBucket: 'goldfish-pos.firebasestorage.app',
    iosBundleId: 'com.example.goldfishPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOTVygWT2VnDWrGrarO4IBoXmhcne_MV8',
    appId: '1:17698616303:web:b2a52f5ef6b0ea747d7c1a',
    messagingSenderId: '17698616303',
    projectId: 'goldfish-pos',
    authDomain: 'goldfish-pos.firebaseapp.com',
    storageBucket: 'goldfish-pos.firebasestorage.app',
    measurementId: 'G-8X040T5J5C',
  );
}
